export const INTEREST_COURSES = [
  'Administração',
  'Agronomia',
  'Análise e Desenvolvimento de Sistemas',
  'Arquitetura e Urbanismo',
  'Artes Cênicas',
  'Artes Visuais',
  'Biologia',
  'Biblioteconomia',
  'Ciências Contábeis',
  'Ciências Econômicas',
  'Ciências Exatas',
  'Ciências Farmacêuticas',
  'Ciências Físicas',
  'Ciências Humanas',
  'Ciências Matemáticas',
  'Ciências Sociais',
  'Comércio Exterior',
  'Comunicação Social',
  'Design Gráfico',
  'Direito',
  'Educação Física',
  'Enfermagem',
  'Engenharia Ambiental',
  'Engenharia Civil',
  'Engenharia de Computação',
  'Engenharia de Controle e Automação',
  'Engenharia de Produção',
  'Engenharia Elétrica',
  'Engenharia Mecânica',
  'Engenharia Química',
  'Filosofia',
  'Física',
  'Geografia',
  'História',
  'Jornalismo',
  'Letras (Português, Inglês, Espanhol, etc)',
  'Medicina',
  'Medicina Veterinária',
  'Música',
  'Nutrição',
  'Odontologia',
  'Pedagogia',
  'Psicologia',
  'Publicidade e Propaganda',
  'Relações Internacionais',
  'Serviço Social',
  'Sistemas de Informação',
  'Terapia Ocupacional',
  'Turismo',
  'Veterinária',
];
