export const INTEREST_UNIVERSITIES = [
  'Academia da Força Aérea (AFA)',
  'Academia Militar das Agulhas Negras (AMAN)',
  'Academia Naval (AN)',
  'Fundação Getúlio Vargas (FGV)',
  'Instituto de Ensino e Pesquisa (Insper)',
  'Instituto Tecnológico de Aeronáutica (ITA)',
  'Pontifícia Universidade Católica de São Paulo (PUC-SP)',
  'Pontifícia Universidade Católica do Rio de Janeiro (PUC-RJ)',
  'Pontifícia Universidade Católica do Rio Grande do Sul (PUC-RS)',
  'Universidade Católica de Pernambuco (UNICAP)',
  'Universidade Cruzeiro do Sul (UNICSUL)',
  'Universidade da Força Aérea (UNIFA)',
  'Universidade de Brasília (UnB)',
  'Universidade de Ribeirão Preto (UNAERP)',
  'Universidade de São Paulo (USP)',
  'Universidade do Estado de São Paulo (UNESP)',
  'Universidade Estadual da Bahia (UNEB)',
  'Universidade Estadual de Campinas (UNICAMP)',
  'Universidade Estadual de Feira de Santana (UEFS)',
  'Universidade Estadual de Goiás (UEG)',
  'Universidade Estadual de Londrina (UEL)',
  'Universidade Estadual de Maringá (UEM)',
  'Universidade Estadual de Mato Grosso do Sul (UEMS)',
  'Universidade Estadual de Montes Claros (UNIMONTES)',
  'Universidade Estadual de Ponta Grossa (UEPG)',
  'Universidade Estadual do Ceará (UECE)',
  'Universidade Estadual do Maranhão (UEMA)',
  'Universidade Estadual do Norte do Paraná',
  'Universidade Estadual do Rio de Janeiro (UERJ)',
  'Universidade Estadual do Rio Grande do Sul (UERGS)',
  'Universidade Estadual do Sudoeste da Bahia (UESB)',
  'Universidade Estadual Paulista (UNESP)',
  'Universidade Federal da Bahia (UFBA)',
  'Universidade Federal da Paraíba (UFPB)',
  'Universidade Federal de Alagoas (UFAL)',
  'Universidade Federal de Amazonas (UFAM)',
  'Universidade Federal de Goiás (UFG)',
  'Universidade Federal de Juiz de Fora (UFJF)',
  'Universidade Federal de Lavras (UFLA)',
  'Universidade Federal de Mato Grosso (UFMT)',
  'Universidade Federal de Mato Grosso do Sul (UFMS)',
  'Universidade Federal de Minas Gerais (UFMG)',
  'Universidade Federal de Pelotas (UFPel)',
  'Universidade Federal de Pernambuco (UFPE)',
  'Universidade Federal de Piauí (UFPI)',
  'Universidade Federal de Roraima (UFRR)',
  'Universidade Federal de Santa Catarina (UFSC)',
  'Universidade Federal de São Carlos (UFSCar)',
  'Universidade Federal de São João del-Rei (UFSJ)',
  'Universidade Federal de Uberlândia (UFU)',
  'Universidade Federal de Viçosa (UFV)',
  'Universidade Federal do ABC (UFABC)',
  'Universidade Federal do Acre (UFAC)',
  'Universidade Federal do Amazonas (UFAM)',
  'Universidade Federal do Ceará (UFC)',
  'Universidade Federal do Espírito Santo (UFES)',
  'Universidade Federal do Maranhão (UFMA)',
  'Universidade Federal do Pará (UFPA)',
  'Universidade Federal do Paraná (UFPR)',
  'Universidade Federal do Rio de Janeiro (UFRJ)',
  'Universidade Federal do Rio Grande (FURG)',
  'Universidade Federal do Rio Grande do Norte (UFRN)',
  'Universidade Federal do Rio Grande do Sul (UFRGS)',
  'Universidade Federal do Sergipe (UFS)',
  'Universidade Federal do Tocantins (UFT)',
  'Universidade Federal Fluminense (UFF)',
  'Universidade Militar de Engenharia (IME)',
  'Universidade Paulista (UNIP)',
  'Universidade Presbiteriana Mackenzie',
  'Universidade São Judas Tadeu (USJT)',
];
